services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    networks:
      - app-network
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d jobtracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    container_name: job-tracker-aws
    image: localstack/localstack:latest
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment: 
      DEBUG: 1
      AWS_DEFAULT_REGION: us-east-1
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
      LAMBDA_DOCKER_FLAGS: "-e AWS_ENDPOINT_URL=http://localstack:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infrastructure/localstack/init:/etc/localstack/init/ready.d
      - ./infrastructure/lambdas:/lambdas
      - localstack_data:/var/lib/localstack
    networks:
      - app-network    

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: postgres
      AWS_ENDPOINT_URL: http://localstack:4566
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_started  

  frontend:
    build: ./frontend
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "4200:8080"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:
  localstack_data: